version: '2.2'
services:
  emartdb:
    image: mysql:8.0.33
    container_name: emartdb
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rza3639
      - MYSQL_DATABASE=books
  
  webapi:
    build:
      context: ./javaapi
    ports:
      - "9000:9000"
    restart: always
    container_name: webapi
    depends_on:
      - emartdb